config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/contact', to: 'static_pages#contact'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get    'sign_in',  to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    post   'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :users do
    resources :basics, only: %i[index show]
    resources :messages, only: %i[create destroy]
    resources :rooms, only: %i[index show create]
    resources :profiles, only: %i[new create edit update]
  end
  namespace :searches do
    resources :users, only: [:index]
    resources :questions, only: [:index] do
      collection do
        # カテゴリーを選択した際のセレクトボックスの動的処理
        get 'get_children_categories_for_search' # 質問検索フォーム用
      end
    end
  end
  namespace :questions do
    resources :posts, only: %i[show new create edit update] do
      member do
        # ベストアンサーを選出する処理
        patch 'select_best_answer'
      end
      collection do
        # カテゴリーを選択した際のセレクトボックスの動的処理
        get 'get_children_categories' # 質問の投稿・編集画面用
      end
    end
    resources :answers, only: %i[index create update]
    resources :replies, only: %i[create update]
    resources :categories, only: [:show]
  end
  namespace :admins do
    resources :users, only: %i[index show destroy] # indexは検索結果画面
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/top.html.erb
<% provide(:title, "Best-Lab") %>

<div class="lp">
  <div class="top">
    <div class="top__container row">
      <div class="top__container--left col-md-6 col-sm-12">
        <p class="top__subtitle">大学研究者のための情報交換サイト</p>
        <h1 class="top__title">Best-Lab</h1>
        <h4 class="top__slogan">研究をもっとおもしろく</h4>
        <div class="top__guest-sign-in">
          <% unless user_signed_in? %>
            <% unless admin_signed_in? %>
              <%= button_to "ゲストユーザーで体験する", users_guest_sign_in_path, method: :post %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="top__container--right col-md-6 col-sm-12">
        <%= image_tag asset_path("top.jpg") %>
      </div>
    </div>
  </div>

  <div class="main-feature">
    <div class="main-feature__container">
      <h3 class="main-feature__title">Best-Labは、研究に携わる大学生の悩みを解決します</h3>
      <p class="main-feature__subtitle">ひとりで悩まず誰かに相談してみましょう</p>
      <ul class="row">
        <li class="col-md-4 col-sm-12">
          <div class="card">
            <h5 class="main-feature__card-title">質問を投稿</h5>
            <i class="fas fa-file-upload"></i>
            <p class="main-feature__card-sentence">研究に行き詰まったら掲示板に質問を投稿してみましょう。有識者がアドバイスをくれるかもしれません。</p>
          </div>
        </li>
        <li class="col-md-4 col-sm-12">
          <div class="card">
            <h5 class="main-feature__card-title">質問を検索</h5>
            <i class="fas fa-search"></i>
            <p class="main-feature__card-sentence">自分と同じ悩みをもつ人が過去に質問を投稿しているかもしれません。検索機能で確認してみてください。</p>
          </div>
        </li>
        <li class="col-md-4 col-sm-12">
          <div class="card">
            <h5 class="main-feature__card-title">安全な情報交換</h5>
            <i class="fas fa-shield-alt"></i>
            <p class="main-feature__card-sentence">研究盗用が心配の方はDMを使った質問が便利。信頼できるユーザーを検索して回答を依頼してみましょう。</p>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="sub-feature">
    <div class="sub-feature__container">
      <div class="sub-feature__img-container row">
        <div class="sub-feature__img-container--left col-md-4 col-sm-12">
          <%= image_tag asset_path("sub-feature.jpg") %>
        </div>
        <div class="sub-feature__img-container--right col-md-8 col-sm-12">
          <h4 class="sub-feature__title">学部生の方もご利用になれます</h4>
          <p>気になる研究室があれば、そこに在籍している先輩に話を聞くことも可能です。研究内容や雰囲気を確認し、自分に合った研究室を見つけてみましょう。</p>
        </div>
      </div>
    </div>
  </div>

<% unless user_signed_in? %>
  <% unless admin_signed_in? %>
    <div class="invitation">
      <div class="invitation__container">
        <h4 class="invitation__title">体験はこちらから！</h4>
          <div class="invitation__button">
            <%= button_to "ゲストユーザーでログイン", users_guest_sign_in_path, method: :post %>
          </div>
      </div>
    </div>
  <% end %>
<% end %>

</div>