config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/contact', to: 'static_pages#contact'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get    'sign_in',  to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    post   'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :users do
    resources :basics, only: %i[index show]
    resources :messages, only: %i[create destroy]
    resources :rooms, only: %i[index show create]
    resources :profiles, only: %i[new create edit update]
  end
  namespace :searches do
    resources :users, only: [:index]
    resources :questions, only: [:index] do
      collection do
        # カテゴリーを選択した際のセレクトボックスの動的処理
        get 'get_children_categories_for_search' # 質問検索フォーム用
      end
    end
  end
  namespace :questions do
    resources :posts, only: %i[show new create edit update] do
      member do
        # ベストアンサーを選出する処理
        patch 'select_best_answer'
      end
      collection do
        # カテゴリーを選択した際のセレクトボックスの動的処理
        get 'get_children_categories' # 質問の投稿・編集画面用
      end
    end
    resources :answers, only: %i[index create update]
    resources :replies, only: %i[create update]
    resources :categories, only: [:show]
  end
  namespace :admins do
    resources :users, only: %i[index show destroy] # indexは検索結果画面
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :question_notices, dependent: :destroy
  belongs_to :user
  belongs_to :category

  STATUS = { open: '受付中', closed: '解決済' }.freeze

  # 自己解決した場合の処理
  def solved_by_questioner
    best_answer = Answer.find_by(post_id: self, user_id: user_id)
    self.status = 'closed'
    self.best_answer_id = best_answer.id
    save
  end

  # 英語名で保存された投稿状態(status)を日本語で表示
  def translated_status
    STATUS[status.to_sym]
  end

  # 質問投稿者用の通知レコードを作成
  def create_notice
    QuestionNotice.create(user_id: user_id, post_id: id)
  end

  # ベストアンサー決定時に回答者全員に通知を送信する
  def send_notice_to_answerers
    answerers = QuestionNotice.where(post_id: self).where.not(user_id: user_id)
    answerers.each do |answerer|
      answerer.update(notice: true) unless answerer.notice
    end
  end

  # 投稿詳細画面に入ると通知が外れる処理
  def remove_notice(user)
    # 通知用レコードがない場合はこの処理をスキップ
    notice = QuestionNotice.find_by(user_id: user, post_id: self)
    notice.update(notice: false) if notice&.notice
  end

  # 投稿への通知の有無を返す処理
  def check_notice(user)
    checked_notice = QuestionNotice.find_by(user_id: user, post_id: self)
    checked_notice&.notice
  end
end

app/controllers/questions/answers_controller.rb
# frozen_string_literal: true

class Questions::AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :restricted_editing_answer, only: :update

  # 回答、リプライした質問を一覧表示
  def index
    @comment_lists = QuestionNotice.sorted_comment_entries(current_user)
    @comment_lists = @comment_lists.page(params[:page])
  end

  # 回答の新規作成
  def create
    @answer = AnswerForm.new
    @answer.assign_attributes(answer_params)
    @post = Post.find(answer_params[:post_id])
    redirect_to root_path if @post.nil? # @postが見つからない場合の処理
    respond_to do |format|
      if @answer.save
        @reply = ReplyForm.new
        @answers = @post.answers
        @post.solved_by_questioner if @post.user_id == @answer.user_id # 自己解決した場合の処理
        answer = Answer.where(user_id: @answer.user_id).last
        answer&.send_notice_to_questioner_or_answerers # 質問に回答した際の通知処理
        format.html { redirect_to questions_post_path(@answer.post_id) }
        format.js
      else
        format.html { render 'questions/posts/show' }
        format.js { render :errors }
      end
    end
  end

  # 回答の編集
  def update
    answer = Answer.find(answer_params[:id])
    @post = Post.find(answer.post_id)
    redirect_to root_path if @post.nil? # @postが見つからない場合の処理
    @answer = AnswerForm.new(answer)
    @answer.assign_attributes(answer_params.except(:id))
    respond_to do |format|
      if @answer.save
        @answers = @post.answers
        format.html { redirect_to questions_post_path(answer.post_id) }
        format.js
      else
        format.html { render 'questions/posts/show' }
        format.js { render :errors }
      end
    end
  end

  private

  def answer_params
    params.require(:answer_form).permit(:id, :body, :post_id, pictures_attributes: [:picture]).merge(user_id: current_user.id)
  end

  # 他人の回答は編集できないよう制限する
  def restricted_editing_answer
    redirect_to users_basic_path(current_user) if current_user.answers.ids.exclude?(params[:id].to_i)
  end
end

app/controllers/questions/categories_controller.rb
# frozen_string_literal: true

class Questions::CategoriesController < ApplicationController
  before_action :check_category_id

  # 1つのカテゴリーに所属する質問を一覧表示する
  def show
    @category = Category.find(params[:id])
    @posts = Post.order(created_at: :desc).where(category_id: @category).page(params[:page])
  end

  private

  # DBに存在しないカテゴリーidを入力した場合はrootにリダイレクトする
  def check_category_id
    redirect_to root_path unless Category.exists?(id: params[:id])
  end
end

app/controllers/questions/posts_controller.rb
# frozen_string_literal: true

class Questions::PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update select_best_answer]
  before_action :restricted_editing_post, only: %i[edit update select_best_answer]
  before_action :set_categories_for_new, only: %i[new create]
  before_action :set_categories_for_edit, only: %i[edit update]

  # 各質問の表示画面
  def show
    @post = Post.find(params[:id])
    @post.remove_notice(current_user) # 投稿詳細画面に入ると通知が外れる処理
    # 回答とそのリプライフォーム用のオブジェクトを定義
    @answer = AnswerForm.new
    @reply = ReplyForm.new
    # ある質問に対するログインユーザーの回答を定義
    @your_answer = Answer.where(post_id: params[:id], user_id: current_user)
    # ある質問に対する回答を定義
    @answers = Answer.where(post_id: params[:id])
  end

  # 投稿の新規作成画面
  def new
    @post_form = PostForm.new
  end

  def create
    @post_form = PostForm.new
    @post_form.assign_attributes(post_params)
    if @post_form.save
      post = Post.where(user_id: current_user).last
      post&.create_notice # 質問投稿者用の通知レコードを作成
      redirect_to users_basic_path(current_user), flash: { notice: '質問を投稿しました。' }
    else
      render :new
    end
  end

  # 投稿の編集画面
  def edit
    @post = Post.find(params[:id])
    @post_form = PostForm.new(@post)
    # すでに作成した投稿のカテゴリーを取得しセレクトボックスに表示する
    @selected_parent_category = @post.category.parent
  end

  def update
    @post = Post.find(params[:id])
    @post_form = PostForm.new(@post)
    @post_form.assign_attributes(post_params)
    if @post_form.save
      redirect_to questions_post_path(@post), flash: { notice: '質問を編集しました。' }
    else
      render :edit
    end
  end

  # 親カテゴリーを選択した際に子カテゴリーを動的に変化させる処理
  def get_children_categories
    @children_categories = Category.find_by(id: params[:parent_category_id].to_s, ancestry: nil).children
  end

  # ベストアンサーを選出する処理
  def select_best_answer
    post = Post.find(params[:id])
    @post_form = PostForm.new(post)
    # ベストアンサー用フォームに不正な値が入力された場合は処理を中断する
    return redirect_to users_basic_path(current_user) if @post_form.check_best_answer_params(post_params) == false

    @post_form.assign_attributes(post_params)
    return unless @post_form.save

    post.send_notice_to_answerers # 回答者全員に通知を送信する
    redirect_to questions_post_path(post), flash: { notice: 'ベストアンサーが決定しました！' }
  end

  private

  def post_params
    params.require(:post_form).permit(:category_id, :title, :content, :status, :best_answer_id, pictures_attributes: [:picture]).merge(user_id: current_user.id)
  end

  # 新規作成画面のセレクトボックスの初期値を表示
  def set_categories_for_new
    @parent_categories = Category.where(ancestry: nil)
    @children_categories = @parent_categories.first&.children
  end

  # 編集画面のセレクトボックスの初期値を表示
  def set_categories_for_edit
    @parent_categories = Category.where(ancestry: nil)
    @children_categories = Post.find(params[:id]).category.parent.children
  end

  # 他人の質問編集画面を閲覧できない、かつ編集できない制限
  def restricted_editing_post
    redirect_to users_basic_path(current_user) if current_user.posts.ids.exclude?(params[:id].to_i)
  end
end

app/controllers/questions/replies_controller.rb
# frozen_string_literal: true

class Questions::RepliesController < ApplicationController
  before_action :authenticate_user!
  before_action :restricted_editing_reply, only: :update

  # リプライの新規作成
  def create
    @reply = ReplyForm.new
    @reply.assign_attributes(reply_params)
    @answer = Answer.find(reply_params[:answer_id])
    redirect_to root_path if @answer.nil? # @answerが見つからない場合の処理
    @post = @answer.post
    respond_to do |format|
      if @reply.save
        @answers = @post.answers
        reply = Reply.where(user_id: @reply.user_id).last
        reply&.send_notice_to_commenter # 回答にリプライした際の通知処理
        format.html { redirect_to questions_post_path(reply.answer.post_id) }
        format.js
      else
        format.html { render 'questions/posts/show' }
        format.js { render :create_errors }
      end
    end
  end

  # リプライの編集
  def update
    # パラメータ中のidをもとに編集するリプライを選出する
    @target_reply = Reply.find(reply_params[:id])
    @reply = ReplyForm.new(@target_reply)
    # パラメータからidを削除してリプライを更新する
    @reply.assign_attributes(reply_params.except(:id))
    @answer = Answer.find(@target_reply.answer_id)
    redirect_to root_path if @answer.nil? # @answerが見つからない場合の処理
    @post = @answer.post
    respond_to do |format|
      if @reply.save
        format.html { redirect_to questions_post_path(@target_reply.answer.post_id) }
        format.js
      else
        format.html { render 'questions/posts/show' }
        format.js { render :update_errors }
      end
    end
  end

  private

  def reply_params
    params.require(:reply_form).permit(:id, :body, :answer_id, pictures_attributes: [:picture]).merge(user_id: current_user.id)
  end

  # 他人のリプライは編集できないよう制限する
  def restricted_editing_reply
    redirect_to users_basic_path(current_user) if current_user.replies.ids.exclude?(params[:id].to_i)
  end
end

app/controllers/searches/questions_controller.rb
# frozen_string_literal: true

class Searches::QuestionsController < ApplicationController
  # 質問の検索一覧を表示
  def index
    if params[:q][:content_cont_any].present?
      params[:q][:content_cont_any] = params[:q][:content_cont_any].split(/[[:blank:]]+/)
    end
    @posts = Post.order(created_at: :desc).ransack(params[:q]).result.page(params[:page])
  end

  # 質問の検索フォームで親カテゴリーを選択した際に子カテゴリーを動的に変化させる処理
  def get_children_categories_for_search
    @children_categories_for_search = Category.find_by(id: params[:parent_category_id].to_s, ancestry: nil).children
  end
end

app/views/questions/posts/edit.html.erb
<% provide(:title, "質問編集") %>

<%= render "questions/shared/post_form", post: @post_form, url: questions_post_path(@post), method: :patch %>

app/views/questions/posts/get_children_categories.js.erb
$('#children_category').html('<%= j(options_for_select(@children_categories.pluck(:name, :id))) %>');

app/views/questions/posts/new.html.erb
<% provide(:title, "質問作成") %>

<%= render "questions/shared/post_form", post: @post_form, url: questions_posts_path, method: :post %>

app/views/questions/posts/show.html.erb
<% provide(:title, @post.title)%>

<div class="display-post">
  <div class="post-container">
    <div class="post-container__post-info">
      <div class="post-container__category">
        <%= link_to(questions_category_path(@post.category_id)) do %>
          <p><%= @post.category.parent.name %> > <%= @post.category.name %></p>
        <% end %>
      </div>
      <div class="post-container__title">
        <h5><%= @post.title %></h5>
      </div>
      <div class="post-container__status">
        <p class="post-status-<%= @post.status %>"><%= @post.translated_status %></p>
        <span>投稿 <%= l @post.created_at, format: :year %></span>
      </div>
    </div>
    <div class="post-container__content">
      <%= @post.content %>
    </div>
    <% unless @post.pictures.blank? %>
      <div class="post-container__pictures">
        <% if @post.pictures.present? %>
          <% @post.pictures.each do |picture| %>
            <%= image_tag asset_path(picture.picture.url), class:"popup-img" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <% if @post.user_id == current_user&.id %>
      <div class="post-container__edit">
        <%= link_to(edit_questions_post_path(@post.id)) do %>
          <i class="fas fa-pen"></i>
          <p>編集</p>
        <% end %>
      </div>
    <% end %>
    <div class="post-container__user-info">
      <%= link_to(users_basic_path(@post.user)) do %>
        <%= image_tag asset_path(@post.user.profile_picture) %>
        <span><%= @post.user.name %></span>
      <% end %>
    </div>
  </div>
</div>

<!-- 質問に対する回答数 -->
<div class="num-of-answers">
  <% if @answers.present? %>
    <h5>回答 <span><%= @answers&.length %></span> 件</h5>
  <% else %>
    <h5>回答はまだついていません</h5>
  <% end %>
</div>

<!-- 回答と回答に紐づいたリプライを表示 -->
<div class="display-comment">
  <% @answers&.each do |answer| %>
    <div class="comment-container">
      <%# 回答%>
      <div class="answer-container">
        <div class="answer-container__details">
          <% if @post.best_answer_id == answer.id %>
            <div class="answer-container__best-answer-title">
              <span>ベストアンサー</span>
            </div>
          <% end %>
          <div id="answer-container__body-<%= answer.id %>" class="answer-container__body">
            <%= answer.body %>
          </div>
          <% unless answer.pictures.blank? %>
            <div id="answer-container__pictures-<%= answer.id %>" class="answer-container__pictures">
              <% answer.pictures.each do |picture| %>
                <%= image_tag asset_path(picture.picture.url), class:"popup-img" %>
              <% end %>
            </div>
          <% end %>
          <div id="edit-answer-form-<%= answer.id %>" class="edit-answer-form hide">
            <%= render "questions/shared/answers/edit_answer_form", answer_form: @answer, answer: answer, post: @post, url: questions_answer_path(answer), method: :patch %>
          </div>
        </div>
        <!-- 回答下部の編集ボタンとユーザー情報 -->
        <% if current_user&.id == answer.user_id %>
          <div class="answer-container__edit">
            <i id="edit-answer-icon-<%= answer.id %>" class="fas fa-pen edit-answer-icon" data-answer-id="<%= answer.id %>"> 編集</i>
          </div>
        <% end %>
        <div class="answer-container__user-info">
          <div class="answer-container__img-and-name">
            <% if current_user&.id == @post.user_id && @post.best_answer_id.blank? %>
              <div id="best-answer-<%= answer.id %>" class="best-answer-button">
                <%= render "questions/shared/best_answer_form", post: PostForm.new, answer: answer, url: select_best_answer_questions_post_path(@post), method: :patch %>
              </div>
            <% end %>
            <%= link_to(users_basic_path(answer.user)) do%>
              <%= image_tag asset_path(answer.user.profile_picture) %>
              <span><%= answer.user.name %></span>
            <% end %>
          </div>
          <div class="answer-container__created_at">
            <span>投稿 <%= l answer.created_at, format: :year %></span>
          </div>
        </div>
      </div>
      <!-- 回答に紐づくリプライ -->
      <div id="reply-container-<%= answer.id %>" class="reply-container">
        <% answer.replies&.order(created_at: :asc).each do |reply| %>
          <div id="reply-container__list-<%= reply.id %>" class="reply-container__list">
            <div id="reply-container__body-<%= reply.id %>" class="reply-container__body">
              <%= reply.body %>
            </div>
            <% unless reply.pictures.blank? %>
              <div id="reply-container__pictures-<%= reply.id %>" class="reply-container__pictures">
                <% reply.pictures.each do |picture| %>
                  <%= image_tag asset_path(picture.picture.url), class:"popup-img" %>
                <% end %>
              </div>
            <% end %>
            <div id="edit-reply-form-<%= reply.id %>" class="edit-reply-form hide">
              <%= render "questions/shared/replies/edit_reply_form", reply_form: @reply, reply: reply, answer: answer, post: @post, url: questions_reply_path(reply), method: :patch %>
            </div>
            <% if current_user&.id == reply.user_id %>
              <div class="reply-container__edit">
                <i id="edit-reply-icon-<%= reply.id %>" class="fas fa-pen edit-reply-icon" data-reply-id="<%= reply.id %>"> 編集</i>
              </div>
            <% end %>
            <!-- リプライ下部のユーザー情報 -->
            <div class="reply-container__user-info">
              <div class="reply-container__img-and-name">
                <%= link_to(users_basic_path(reply.user)) do %>
                  <%= image_tag asset_path(reply.user.profile_picture) %>
                  <span><%= reply.user.name %></span>
                <% end %>
              </div>
              <div class="reply-container__created_at">
                <span>投稿 <%= l reply.created_at, format: :year %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%= render "questions/shared/replies/new_reply_form", reply: @reply, answer: answer, post: @post, url: questions_replies_path, method: :post %>
    </div>
  <% end %>
</div>
<div id="popup-background"></div>
<img id="popup-item" src="" />

<div id="your-answer">
  <!-- 自分の質問以外の質問に対して、まだ回答していない場合は回答用のフォームを表示 -->
  <% if @your_answer.blank? && @post.user_id != current_user&.id %>
    <h4 class="your-answer__title">あなたの回答</h4>
    <%= render "questions/shared/answers/new_answer_form", reply: @reply, answer: @answer, url: questions_answers_path, method: :post %>
  <% end %>

  <!-- 自分の質問を自己解決できた場合に解決方法を記入するフォームを表示 -->
  <% if @your_answer.blank? && @post.user_id == current_user&.id %>
    <h4 class="your-answer__title">解決方法（自己解決の場合のみ記入してください）</h4>
    <%= render "questions/shared/answers/new_answer_form", reply: @reply, answer: @answer, url: questions_answers_path, method: :post %>
  <% end %>
</div>