config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get  '/contact', to: 'static_pages#contact'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get    'sign_in',  to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
    post   'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  namespace :users do
    resources :basics, only: %i[index show]
    resources :messages, only: %i[create destroy]
    resources :rooms, only: %i[index show create]
    resources :profiles, only: %i[new create edit update]
  end
  namespace :searches do
    resources :users, only: [:index]
    resources :questions, only: [:index] do
      collection do
        # カテゴリーを選択した際のセレクトボックスの動的処理
        get 'get_children_categories_for_search' # 質問検索フォーム用
      end
    end
  end
  namespace :questions do
    resources :posts, only: %i[show new create edit update] do
      member do
        # ベストアンサーを選出する処理
        patch 'select_best_answer'
      end
      collection do
        # カテゴリーを選択した際のセレクトボックスの動的処理
        get 'get_children_categories' # 質問の投稿・編集画面用
      end
    end
    resources :answers, only: %i[index create update]
    resources :replies, only: %i[create update]
    resources :categories, only: [:show]
  end
  namespace :admins do
    resources :users, only: %i[index show destroy] # indexは検索結果画面
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # 論理削除用のgem discardを導入
  include Discard::Model

  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length: { maximum: 50 }
  has_one :profile, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :question_notices, dependent: :destroy

  # アカウント認証が済むまでログインできない処理
  def active_for_authentication?
    super && confirmed?
  end

  # 上記のメソッドがfalseを返した場合にエラーメッセージを表示する処理
  def inactive_message
    confirmed? ? super : :unconfirmed
  end

  # 現在のパスワード入力なしでアカウント情報を更新
  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update(params, *options)
    clean_up_passwords
    result
  end

  # ゲストユーザーでログインする際に必要なデータを作成
  def self.guest
    find_or_create_by!(name: 'guest', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.current
    end
  end

  # ユーザーの退会処理
  def inactivate_account
    update(name: '退会済みユーザー')
    discard
  end

  # 退会したユーザーに紐づく投稿と追知を削除
  def inactivate_comments_and_notices
    secondary_array = [posts, answers, replies, question_notices]
    secondary_array.each do |array|
      array.each do |element|
        element.destroy
      end
    end
  end

  # プロフィール画像の有無で表示する画像を変化する処理
  def profile_picture
    picture.present? ? picture.url : 'default.jpg'
  end
end

app/controllers/admins/users_controller.rb
# frozen_string_literal: true

class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :check_user, only: %i[show destroy]

  def index
    params[:q][:name_cont_any] = params[:q][:name_cont_any].split(/[[:blank:]]+/) if params[:q][:name_cont_any].present?
    @users = User.ransack(params[:q]).result.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  # 特定のユーザーの情報を削除する
  def destroy
    user = User.find(params[:id])
    user.inactivate_account
    user.inactivate_comments_and_notices
    redirect_to admins_user_path(user)
  end

  private

  # DBに存在しないユーザーidを入力するとrootにリダイレクト
  def check_user
    redirect_to root_path unless User.exists?(id: params[:id])
  end
end

app/controllers/searches/users_controller.rb
# frozen_string_literal: true

class Searches::UsersController < ApplicationController
  before_action :authenticate_user!

  # ユーザーの検索一覧を表示
  def index
    if params[:q][:description_cont_any].present?
      params[:q][:description_cont_any] = params[:q][:description_cont_any].split(/[[:blank:]]+/)
    end
    # 所属が未選択の場合は全検索とする
    params[:q][:affiliation_eq].clear if params[:q][:affiliation_eq] == 'unselected'
    @profiles = Profile.ransack(params[:q]).result.page(params[:page])
  end
end

app/controllers/users/basics_controller.rb
# frozen_string_literal: true

class Users::BasicsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_id
  before_action :restricted_viewing_deleted_user

  def show
    @user = User.find(params[:id])
    # 共通のメッセージルームを持つ場合はroom_idを返す
    @room_id = Entry.find_room_id(current_user, @user) if current_user != @user
    # room_idがない場合はルーム作成フォーム用のインスタンスを生成
    @entry = Entry.new if @room_id.nil?
    # ユーザーが投稿した質問を降順で表示
    @posts = Post.where(user_id: @user).order(created_at: :desc).page(params[:page])
  end
end

  private

# DBに存在しないユーザーidを入力した場合はrootにリダイレクトする
def check_user_id
  redirect_to root_path unless User.exists?(id: params[:id])
end

# 退会済みのユーザーの画面は表示できないように制限
def restricted_viewing_deleted_user
  redirect_to root_path if User.find(params[:id]).discarded?
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # メールによる承認完了後はログイン状態にする
  def show
    super { |resource| sign_in(resource) }
  end

  protected

  # アカウント有効化申請メール送信後はrootにリダイレクトする
  def after_resending_confirmation_instructions_path_for(_resource_name)
    root_path
  end

  # アカウント認証後はユーザー詳細画面にリダイレクトする
  def after_confirmation_path_for(_resource_name, _resource)
    users_basic_path(current_user)
  end
end

app/controllers/users/messages_controller.rb
# frozen_string_literal: true

class Users::MessagesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :restricted_sending_message, only: :create
  before_action :restricted_destroying_message, only: :destroy

  def create
    @message = MessageForm.new
    @message.assign_attributes(message_form_params)
    if @message.save
      message = Message.where(user_id: current_user).last
      message&.send_notice_to_partner # メッセージ相手に通知を送信する処理
      redirect_to users_room_path(@message.room_id)
    else
      @room = Room.find(@message.room_id)
      @another_entry = @room.entries.partner_of(current_user)
      redirect_to root_path if @room.nil? || @another_entry.nil? # roomとentryが見つからなかった場合の処理
      render 'users/rooms/show'
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to users_room_path(message.room_id)
  end

  private

  def message_form_params
    params.require(:message_form).permit(:room_id, :body, pictures_attributes: [:picture]).merge(user_id: current_user.id)
  end

  # 他人のメッセージルームにメッセージを送信できない制限
  def restricted_sending_message
    room_ids = current_user.entries.map(&:room_id)
    redirect_to root_path if room_ids.exclude?(message_form_params[:room_id].to_i)
  end

  # 他人のメッセージは削除できない制限
  def restricted_destroying_message
    redirect_to users_basic_path(current_user) if current_user.messages.ids.exclude?(params[:id].to_i)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: [:create]

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  # パスワード再設定後はユーザー詳細ページにリダイレクトする
  def after_resetting_password_path_for(_resource)
    users_basic_path(current_user)
  end

  # パスワード再設定メール送信後はrootにリダイレクトする
  def after_sending_reset_password_instructions_path_for(_resource_name)
    root_path
  end

  # ゲストユーザーはパスワード変更のメールを送れず、変更もできない
  def check_guest
    redirect_to new_user_password_path, alert: 'ゲストユーザーのパスワードは変更できません。' if params[:user][:email] == 'guest@example.com'
  end
end

app/controllers/users/profiles_controller.rb
# frozen_string_literal: true

class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :restricted_profile_editing, only: %i[edit update]
  before_action :restricted_guest_profile_editing, only: [:update]

  # プロフィール新規作成画面
  def new
    @profile_form = ProfileForm.new
  end

  # プロフィール作成
  def create
    @profile_form = ProfileForm.new
    @profile_form.assign_attributes(profile_form_params)
    if @profile_form.save
      redirect_to users_basic_path(current_user), flash: { notice: 'プロフィールを保存しました。' }
    else
      render :new
    end
  end

  # プロフィール編集画面
  def edit
    # ログインユーザーのプロフィール情報を取得
    @profile = Profile.find(params[:id])
    @profile_form = ProfileForm.new(@profile)
  end

  # プロフィール編集
  def update
    @profile = Profile.find(params[:id])
    @profile_form = ProfileForm.new(@profile)
    # 複数のattributeをまとめて更新
    @profile_form.assign_attributes(profile_form_params)
    if @profile_form.save
      redirect_to users_basic_path(current_user), flash: { notice: 'プロフィールを保存しました。' }
    else
      render :edit
    end
  end

  private

  def profile_form_params
    params.require(:profile_form).permit(:affiliation, :school, :faculty, :department, :laboratory, :description).merge(user_id: current_user.id)
  end

  # 他人のプロフィールを編集できないようにする
  def restricted_profile_editing
    redirect_to users_basic_path(current_user) if current_user.profile != Profile.find(params[:id])
  end

  # ゲストユーザーのプロフィールは編集できないようにする
  def restricted_guest_profile_editing
    if current_user.email == 'guest@example.com'
      redirect_to users_basic_path(current_user), alert: 'ゲストユーザーのプロフィールは編集できません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!, only: %i[edit update destroy]
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # アカウントの削除
  def destroy
    current_user.inactivate_account
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message! :notice, :destroyed
    respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # 新規登録時のストロングパラメータを定義
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # アカウント更新時のストロングパラメータを定義
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name picture])
  end

  # アカウント更新後はユーザー詳細画面にリダイレクトする
  def after_update_path_for(_resource)
    users_basic_path(current_user)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   users_path
  # end

  # 新規登録時はアカウント認証が完了していないので、rootにリダイレクトする
  def after_inactive_sign_up_path_for(_resource)
    root_path
  end

  # パスワード入力なしでアカウント情報を更新する
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # ゲストユーザーの場合は削除できないようにする
  def check_guest
    redirect_to users_basic_path(current_user), alert: 'ゲストユーザーの編集・削除はできません。' if resource.email == 'guest@example.com'
  end
end

app/controllers/users/rooms_controller.rb
# frozen_string_literal: true

class Users::RoomsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show create]
  before_action :restricted_room_viewing, only: [:show]

  def create
    # メッセージルームを作成
    room = Room.create
    # Entryモデルにログインユーザーのレコードを作成
    @current_entry = Entry.create(user_id: current_user.id, room_id: room.id)
    # Entryモデルに相手のレコードを作成
    @another_entry = Entry.create(user_id: entry_params[:user_id], room_id: room.id)
    # 作成した部屋を表示
    redirect_to users_room_path(room)
  end

  def index
    # メッセージ相手と部屋の情報を取得
    @another_entries = Entry.another_entries(current_user)
    # 最後にやりとりしたメッセージが新しい順にソート
    @sorted_entries = @another_entries.sorted_entries(current_user)
  end

  def show
    @room = Room.find(params[:id])
    @room&.remove_notice(current_user) # メッセージルームに入ると通知が外れる処理
    @message = MessageForm.new # formのmodelに入れるオブジェクトを作成
    @another_entry = @room.entries.partner_of(current_user) # メッセージ相手と部屋の情報を取得
    redirect_to root_path if @another_entry.nil? # 相手の情報がなかった場合の処理
  end

  private

  def entry_params
    params.require(:entry).permit(:user_id)
  end

  # 他人のメッセージルームを閲覧できないよう制限
  def restricted_room_viewing
    current_room_ids = current_user.entries.map(&:room_id)
    redirect_to users_basic_path(current_user) if current_room_ids.exclude?(params[:id].to_i)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: :create
  before_action :restricted_sign_in_by_deleted_user, only: :create

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # ゲストユーザーでログインするための処理
  def new_guest
    user = User.guest
    sign_in user
    redirect_to users_basic_path(user), notice: 'ゲストユーザーでログインしました。'
  end

  protected

  # ログイン用のストロングパラメータを定義
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in)
  end

  # ログイン後はユーザー詳細画面にリダイレクトする
  def after_sign_in_path_for(_resource_name)
    users_basic_path(current_user)
  end

  # ログアウト後はrootにリダイレクトする
  def after_sign_out_path_for(_resource_name)
    root_path
  end

  # 退会済みのユーザーはログインできないように制限
  def restricted_sign_in_by_deleted_user
    user = User.find_by(email: params[:user][:email])
    redirect_to new_user_registration_path if user && user.discarded? # ユーザーは見つかるが退会済みの場合
  end
end

app/controllers/users/users_controller.rb
# frozen_string_literal: true

class Users::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_edit_profile_form.html.erb
<div class="common-form">
  <div class="common-form__container">
    <h4>プロフィール設定</h4>
    <%= form_with model: profile_form, url: url, method: method,  local: true do |f| %>
      <%= render "users/shared/error_messages", resource: profile_form %>

      <div class="field">
        <%= f.label :affiliation %>
        <div class="select-container">
          <%= f.select(:affiliation, ProfileForm::AFFILIATIONS.invert, selected: profile.affiliation) %>
        </div>
      </div>

      <div class="field">
        <%= f.label :school %><br />
        <%= f.text_field :school, value: "#{profile.school}" %>
      </div>

      <div class="field">
        <%= f.label :faculty %><br />
        <%= f.text_field :faculty, value: "#{profile.faculty}" %>
      </div>

      <div class="field">
        <%= f.label :department %><br />
        <%= f.text_field :department, value: "#{profile.department}" %>
      </div>

      <div class="field">
        <%= f.label :laboratory %><br />
        <%= f.text_field :laboratory, value: "#{profile.laboratory}" %>
      </div>

      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, value: "#{profile.description}" %>
      </div>

      <div class="actions">
        <%= f.submit "保存" %>
      </div>

    <% end%>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<div class="links-container">
  <%- if controller_name != 'sessions' %>
    <%= link_to "ログイン", new_session_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "新規登録", new_registration_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "本人確認のメールが届かない、またはメールを紛失した方はこちら", new_confirmation_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/users/shared/_message_field.html.erb
<div class="message-field__content">
  <div class="message-field__profile">
    <% if message.user_id != current_user.id %>
      <%= link_to(users_basic_path(message.user)) do %>
        <%= image_tag asset_path(message.user.profile_picture) %>
      <% end %>
    <% end %>
  </div>
  <div id="message-id-<%= message.id %>" class="message-field__message" >
    <%= simple_format(message.body) %>
    <% message.pictures.each do |message_picture| %>
      <%= image_tag asset_path(message_picture.picture.url) , class:"popup-img"%>
    <% end %>
  </div>
  <div class="message-field__created_at">
    <p><%= l message.created_at %></p>
  </div>
  <% if message.user_id == current_user.id %>
    <div id ="message-id-<%= message.id %>__menu" class="message-field__menu">
      <ul>
        <li>
          <%= form_for(@message, url: users_message_path(message.id), method: :delete, local: true) do |f| %>
            <%= f.submit "削除", data: { confirm: "本当に削除しますか？"} %>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
</div>
<br />

app/views/users/shared/_new_profile_form.html.erb
<div class="common-form">
  <div class="common-form__container">
    <h4>プロフィール設定</h4>
    <%= form_with model: profile_form, url: url, method: method,  local: true do |f| %>
      <%= render "users/shared/error_messages", resource: profile_form %>

      <div class="field">
        <%= f.label :affiliation %>
        <div class="select-container">
          <%= f.select(:affiliation, ProfileForm::AFFILIATIONS.invert) %>
        </div>
      </div>

      <div class="field">
        <%= f.label :school %><br />
        <%= f.text_field :school %>
      </div>

      <div class="field">
        <%= f.label :faculty %><br />
        <%= f.text_field :faculty %>
      </div>

      <div class="field">
        <%= f.label :department %><br />
        <%= f.text_field :department %>
      </div>

      <div class="field">
        <%= f.label :laboratory %><br />
        <%= f.text_field :laboratory %>
      </div>

      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description %>
      </div>

      <div class="actions">
        <%= f.submit "保存" %>
      </div>

    <% end%>
  </div>
</div>

app/views/users/shared/_search_form.html.erb
<h4>ユーザー検索</h4>

<%= search_form_for @profile_search, url: searches_users_path do |f| %>

  <div class="field">
    <%= f.label :affiliation_eq, "所属" %>
    <div class="side-select-container">
      <%= f.select(:affiliation_eq, ProfileForm::AFFILIATIONS.invert) %>
    </div>
  </div>

  <div class="field">
    <%= f.label :school_eq, "学校名" %><br />
    <%= f.text_field :school_eq %>
  </div>

  <div class="field">
    <%= f.label :faculty_eq, "学部・研究科名" %><br />
    <%= f.text_field :faculty_eq %>
  </div>

  <div class="field">
    <%= f.label :department_eq, "学科・専攻・コース名" %><br />
    <%= f.text_field :department_eq %>
  </div>

  <div class="field">
    <%= f.label :laboratory_eq, "研究室名" %><br />
    <%= f.text_field :laboratory_eq %>
  </div>

  <div class="field">
    <%= f.label :description_cont_any, "プロフィール・研究分野など" %><br />
    <p>(スペース区切りで複数検索できます)</p>
    <%= f.text_field :description_cont_any %>
  </div>

  <div class="actions">
    <%= f.submit "検索" %>
  </div>

<% end%>